name: Run Postman Tests and Publish Report

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman & Reporter
        run: |
          npm install -g newman newman-reporter-html

      - name: Run Postman Collection
        run: |
          newman run petstore.collection.json \
            --reporters cli,html \
            --reporter-html-export report.html

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: postman-report
          path: report.html

  deploy-report:
    needs: run-postman
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: postman-report
          path: ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
